[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@reality/=lib/reality-kaia/packages/protocol/src/"
]
solc_version = "0.8.23"

[rpc_endpoints]
localhost = "http://localhost:8545"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[test]
verbosity = 2
fuzz = { runs = 256 }
invariant = { runs = 256 }
